'use client';

import React from 'react';
import { X, Printer, Send, Edit, Plus, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Invoice } from '@/services/purchaseDummyData';

interface InvoiceDetailModalProps {
    invoice: Invoice;
    onClose: () => void;
    onBack: () => void;
}

const InvoiceDetailModal: React.FC<InvoiceDetailModalProps> = ({ invoice, onClose, onBack }) => {
    return (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-5xl h-[90vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
                {/* Header Toolbar */}
                <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-white">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" size="sm" onClick={onBack} className="text-slate-500 hover:text-slate-800 gap-2">
                            <ArrowLeft size={16} /> Back
                        </Button>
                        <h2 className="text-xl font-bold text-slate-800">Purchase Invoice # <span className="text-slate-500 font-normal text-lg">{invoice.id}</span></h2>
                    </div>
                    <div className="flex items-center gap-2">
                        <button onClick={onClose} className="ml-2 p-2 transition-colors rounded-full hover:bg-slate-100 text-slate-500">
                            <X size={20} />
                        </button>
                    </div>
                </div>

                {/* Scrollable Content */}
                <div className="flex-1 overflow-y-auto custom-scrollbar p-8 bg-slate-50/50">
                    <div className="max-w-4xl mx-auto space-y-6">

                        {/* Status Banner */}
                        <div className={`w-full py-2 px-4 rounded text-center font-bold text-sm uppercase tracking-widest ${invoice.status === 'Paid' ? 'bg-green-100 text-green-700' :
                            invoice.status === 'Due' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700'
                            }`}>
                            Status: {invoice.status}
                        </div>

                        {/* Invoice Info Cards */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {/* Left: General Info */}
                            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm space-y-3 text-sm">
                                <div className="grid grid-cols-3 gap-4">
                                    <span className="font-semibold text-slate-600">Purchase Date</span>
                                    <span className="col-span-2 text-slate-900">{invoice.purchaseDate}</span>
                                </div>
                                <div className="grid grid-cols-3 gap-4">
                                    <span className="font-semibold text-slate-600">Supplier Name</span>
                                    <span className="col-span-2 text-slate-900 font-medium">{invoice.supplierName}</span>
                                </div>
                                <div className="grid grid-cols-3 gap-4">
                                    <span className="font-semibold text-slate-600">Supplier Phone</span>
                                    <span className="col-span-2 text-slate-900">{invoice.supplierContact}</span>
                                </div>
                                <div className="grid grid-cols-3 gap-4">
                                    <span className="font-semibold text-slate-600">Generated By</span>
                                    <span className="col-span-2 text-slate-900">Admin User</span>
                                </div>
                            </div>

                            {/* Right: Company Header (Visual) */}
                            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm text-right flex flex-col justify-center">
                                <h3 className="text-xl font-bold text-slate-800">Family Health Care</h3>
                                <p className="text-slate-500 text-xs mt-1">507/1, Uttar Ibrahimpur, Mirpur-14, Dhaka-1206</p>
                                <p className="text-slate-500 text-xs">Dhaka, Mirpur, Dhaka, BD</p>
                            </div>
                        </div>

                        {/* Items Table */}
                        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                            <table className="w-full text-sm">
                                <thead className="bg-slate-50 border-b border-slate-200">
                                    <tr>
                                        <th className="px-6 py-3 text-left font-semibold text-slate-600">Item Details</th>
                                        <th className="px-6 py-3 text-center font-semibold text-slate-600">Qty</th>
                                        <th className="px-6 py-3 text-right font-semibold text-slate-600">Unit Price</th>
                                        <th className="px-6 py-3 text-right font-semibold text-slate-600">Total (BDT)</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-100">
                                    {invoice.items.map((item) => (
                                        <tr key={item.id}>
                                            <td className="px-6 py-4">
                                                <div className="font-medium text-slate-800">{item.name}</div>
                                                <div className="text-xs text-slate-500">{item.strength}</div>
                                            </td>
                                            <td className="px-6 py-4 text-center text-slate-600">{item.qty}</td>
                                            <td className="px-6 py-4 text-right text-slate-600">{item.unitPrice.toFixed(2)}</td>
                                            <td className="px-6 py-4 text-right text-slate-800 font-medium">{item.total.toFixed(2)}</td>
                                        </tr>
                                    ))}
                                </tbody>
                                {/* Footer Calculations */}
                                <tfoot className="bg-slate-50/50">
                                    <tr>
                                        <td colSpan={3} className="px-6 py-2 text-right text-slate-600 font-medium border-t border-slate-200">Total Trade Amount</td>
                                        <td className="px-6 py-2 text-right text-slate-800 font-bold border-t border-slate-200">{invoice.subtotal.toFixed(2)}</td>
                                    </tr>
                                    <tr className="bg-blue-50/50">
                                        <td colSpan={3} className="px-6 py-3 text-right text-slate-800 font-bold border-t border-blue-100">Grand Total</td>
                                        <td className="px-6 py-3 text-right text-blue-700 font-bold text-lg border-t border-blue-100">{invoice.totalAmount.toFixed(2)}</td>
                                    </tr>
                                    <tr>
                                        <td colSpan={3} className="px-6 py-2 text-right text-slate-600 font-medium">Total Paid</td>
                                        <td className="px-6 py-2 text-right text-green-600 font-bold">{invoice.paidAmount.toFixed(2)}</td>
                                    </tr>
                                    <tr>
                                        <td colSpan={3} className="px-6 py-2 text-right text-slate-600 font-medium">Amount Due</td>
                                        <td className="px-6 py-2 text-right text-red-600 font-bold">{invoice.dueAmount.toFixed(2)}</td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>

                        {/* Transactions Table */}
                        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden p-6">
                            <h4 className="text-sm font-bold text-slate-800 mb-4">Related Transactions</h4>
                            <div className="overflow-x-auto">
                                <table className="w-full text-xs">
                                    <thead className="bg-slate-50">
                                        <tr>
                                            <th className="px-4 py-2 text-left font-semibold text-slate-600">Date</th>
                                            <th className="px-4 py-2 text-left font-semibold text-slate-600">Payment Method</th>
                                            <th className="px-4 py-2 text-left font-semibold text-slate-600">Account</th>
                                            <th className="px-4 py-2 text-right font-semibold text-slate-600">Amount (BDT)</th>
                                            <th className="px-4 py-2 text-left font-semibold text-slate-600 pl-8">Description</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-100">
                                        {invoice.transactions.length > 0 ? invoice.transactions.map((tx, idx) => (
                                            <tr key={idx}>
                                                <td className="px-4 py-3 text-slate-600">{tx.date}</td>
                                                <td className="px-4 py-3 text-slate-600">{tx.paymentMethod}</td>
                                                <td className="px-4 py-3 text-slate-600">{tx.account}</td>
                                                <td className="px-4 py-3 text-right text-slate-800 font-medium">{tx.amount.toFixed(2)}</td>
                                                <td className="px-4 py-3 text-slate-500 pl-8">{tx.description}</td>
                                            </tr>
                                        )) : (
                                            <tr>
                                                <td colSpan={5} className="px-4 py-8 text-center text-slate-400 italic">No transactions found</td>
                                            </tr>
                                        )}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    );
};

export default InvoiceDetailModal;
